### ISSUE TITLE
Error in repo init & sync

### ISSUE THREAD

**Issue by Aldair502** [TheXPerienceProject/Manifest#9]
fatal: manifest 'default.xml' not available
fatal: remove-project element specifies non-existent project: < remove-project name="platform/packages/Settings"/>

Repo command failed: UpdateManifestError
	Unable to sync manifest default.xml

I mean i have no problem with it since i can solve it
changing it to /packages/apps

**Comment by Aldair502** [comment]
Also i want to add this 
Fetching:  0% (0/1) 0:05 | 1 job | 0:04 android_hardware_xperience_interfaces @ hardware/xperience/interfaces
fatal: no se pudo encontrar ref remota refs/heads/xpe-18.0-caf

android_hardware_xperience_interfaces:
fatal: no se pudo encontrar ref remota refs/heads/xpe-18.0-caf
android_hardware_xperience_interfaces: sleeping 4.0 seconds before retrying
fatal: no se pudo encontrar ref remota refs/heads/xpe-18.0-caf
error: Cannot fetch android_hardware_xperience_interfaces from https://github.com/TheXPerienceProject/android_hardware_xperience_interfaces

**Comment by Klozz** [comment]
let me check 
in 1 hour

**Comment by Klozz** [comment]
Fixed sorry i was busy :/
